export const GET_NOW_PLAYING_MOVIES_START = "GET_NOW_PLAYING_MOVIES_START";
export const GET_UPCOMING_MOVIES_START = "GET_UPCOMING_MOVIES_START";
export const GET_POPULAR_MOVIES_START = "GET_POPULAR_MOVIES_START";

export const GET_NOW_PLAYING_MOVIES_SUCCESS = "GET_NOW_PLAYING_MOVIES_SUCCESS";
export const GET_UPCOMING_MOVIES_SUCCESS = "GET_UPCOMING_MOVIES_SUCCESS";
export const GET_POPULAR_MOVIES_SUCCESS = "GET_POPULAR_MOVIES_SUCCESS";

export const GET_NOW_PLAYING_MOVIES_ERROR = "GET_NOW_PLAYING_MOVIES_ERROR";
export const GET_UPCOMING_MOVIES_ERROR = "GET_UPCOMING_MOVIES_ERROR";
export const GET_POPULAR_MOVIES_ERROR = "GET_POPULAR_MOVIES_ERROR";

export const RESET_MOVIES = "RESET_MOVIES";

export const NUMBER_OF_FILMS_IN_LIST = 5;

export enum moviesType {
  nowPlaying = "now_playing",
  upcoming = "upcoming",
  popular = "popular",
}
